# docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./persons.db
      - SENTRY_DSN=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           # Ersätt med din Sentry DSN
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      - GOOGLE_CHROME_SHIM=/usr/bin/google-chrome
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./persons.db
      - SENTRY_DSN=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           # Ersätt med din Sentry DSN
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      - GOOGLE_CHROME_SHIM=/usr/bin/google-chrome
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
